global:
  scrape_interval: 5s

scrape_configs:
  - job_name: vmsingle
    static_configs:
      - targets: 
          - '127.0.0.1:8428'

  - job_name: jaeger
    static_configs:
      - targets:
          - 'jaeger:8889'